AprendiendoDjango/posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [
    path('', views.PostsFeedView.as_view(), name='index'),
    path('posts/<slug:url>/', views.PostDetailView.as_view(), name='detail'),
    path('posts/save_comment/', views.save_comment, name='save_comment'),
]

AprendiendoDjango/users/urls.py
"""Users URLs."""

# Django
from django.urls import path
from django.views.generic import TemplateView
# View
from users import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.SignupView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('registerok/', TemplateView.as_view(template_name='users/registerok.html'), name='registerok'),
]

AprendiendoDjango/web_xurxo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sobre-mi/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('', include(('users.urls', 'users'), namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AprendiendoDjango/templates/about.html
{% extends "base.html" %}
{% block title %}Web Xurxo - Sobre min{% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h1 class="mt-4">Sobre min</h1>
        <hr>
        <img class="img-fluid rounded" src="http://placehold.it/150x200" alt="">
        <hr>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>
        <hr>
      </div>
{% endblock %}

AprendiendoDjango/templates/base.html
<!DOCTYPE html>
<html lang="es">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <link rel="icon" type="image/jpg" href="https://static.vecteezy.com/ti/vecteur-libre/p1/15021448-icone-de-site-web-isole-sur-fond-blanc-gratuit-vectoriel.jpg">
      <title>{% block title %}Simple blog{% endblock %}</title>
      <!-- Cargamos bootstrap4 e o css de static -->
      {% load bootstrap4 static %}
      {% bootstrap_css %}
      <link rel="stylesheet" href="{% static 'css/blog-home.css' %}">
   </head>
   <body>
      <!-- Menú de navegación -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
         <div class="container">
            <a class="navbar-brand" href="{% url 'posts:index' %}">Web Xurxo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
               <ul class="navbar-nav ml-auto">
                  <li class="nav-item active">
                     <a class="nav-link" href="{% url 'posts:index' %}">Blog
                     <span class="sr-only">(current)</span>
                     </a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'about' %}">Sobre min</a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{request.user.username}}</a>
                     <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                     </div>
                  </li>
                  {% else %}
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'users:register' %}">Rexistro</a>
                  </li>
                  {% endif %}
               </ul>
            </div>
         </div>
      </nav>
      <!-- Page Content -->
      <div class="container">
        <div class="row">
          <!-- Bloque donde cargaremos o contido da páxina -->
          {% block content %}{% endblock %}
          <!-- Columna Widgets barra laterais -->
          <div class="col-md-4">
            <!-- Widget Categorias -->
            <div class="card my-4">
              <h5 class="card-header">Categorías</h5>
              <div class="card-body">
                <div class="row">
                    <div class="col-lg-12">
                      <ul class="list-unstyled mb-0">
                        {% for category in categories %}
                        <li>
                            <a href="#">{{category.name}}</a>
                        </li>
                        {% endfor %}
                      </ul>
                    </div>
                </div>
              </div>
            </div>
            <!-- Widget lateral -->
            <div class="card my-4">
                <h5 class="card-header">Widget latereal</h5>
                <div class="card-body">
                  Podes colocar o que quieras dentro destes widgets laterais. Son fáciles de usar e incluen os novos contedores de tarxetas de Bootstrap 4!
                </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Footer -->
      <footer class="py-5 bg-dark">
         <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Web Xurxo {% now "Y" %}</p>
         </div>
         <!-- /.container -->
      </footer>
      {% bootstrap_javascript jquery='full' %}
   </body>
</html>